# Generated by Django 4.2.6 on 2023-11-18 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openapi', '0004_alter_openapifile_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedHTTPMethods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=255)),
                ('openapi_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openapi.openapifile')),
            ],
        ),
    ]
